apiVersion: v1
kind: ConfigMap
metadata:
  name: urlshortener-config-dev
data:
  ENV_MARKER: "LOCAL CONFIGURATION - k8s"
  APP_HOST: "http://localhost:8080"
  API_URL: "/api/v1"
  DB_SKIP_INITIALISATION: "false"
  DB_USER: "iponomarev"
  DB_PASSWORD: ""
  DB_DRIVER: "org.h2.Driver"
  DB_URL: "jdbc:h2:mem:test;DB_CLOSE_DELAY=-1;"
  DB_MAXIMUM_POOL_SIZE: "5"