apiVersion: apps/v1
kind: Deployment
metadata:
  name: urlshortener
spec:
  replicas: 3
  selector:
    matchLabels:
      app: urlshortener
  template:
    metadata:
      labels:
        app: urlshortener
    spec:
      containers:
        - name: urlshortener
          image: urlshortener:prod
          envFrom:
            - configMapRef:
                name: urlshortener-config-prod
          ports:
            - containerPort: 8080