env_marker: "LOCAL CONFIGURATION"

ktor:
  application:
    modules:
      - com.iponomarev.ApplicationKt.module
  deployment:
    port: 8080

app:
  skipMetrics: true
  version: 1.0
  host: "http://localhost:8080"
  apiUrl: "/api/v1"

db:
  skipInitialisation: false
  user: "iponomarev"
  password: ""
  driver: "org.h2.Driver"
  url: "jdbc:h2:mem:test;DB_CLOSE_DELAY=-1;"
  maximumPoolSize: 5
  expirationTimeDays: 30
  cleanupIntervalHours: 24