env_marker: "DEV CONFIGURATION"

ktor:
  application:
    modules:
      - com.iponomarev.ApplicationKt.module
  deployment:
    port: 8080

app:
  host: "https://dev.shortify.com"
  apiUrl: "/api/v1"

db:
  skipInitialisation: false
  user: "iponomarev"
  password: ""
  driver: "org.h2.Driver"
  url: "jdbc:h2:mem:test;DB_CLOSE_DELAY=-1;"
  maximumPoolSize: 5