env_marker: "LOCAL CONFIGURATION"

ktor:
  application:
    modules:
      - com.iponomarev.ApplicationKt.module
  deployment:
    port: 8080

app:
  host: "http://localhost:8080"

db:
  skipInitialisation: false
  user: "iponomarev"
  password: ""
  driver: "org.h2.Driver"
  url: "jdbc:h2:mem:test;DB_CLOSE_DELAY=-1;"